trigger:
- none  # O cambia a 'main' si quieres que se ejecute con cada push

pool:
  name: Default  # Asegúrate de que 'testlinux' esté en este pool

jobs:
- job: ExpandirRootPartition
  displayName: "Expandir partición raíz automáticamente"
  timeoutInMinutes: 20

  steps:
  - script: |
      echo "=== Información inicial del disco ==="
      lsblk
      df -h /
      echo ""

      echo "=== Expandir partición /dev/sda3 ==="
      sudo growpart /dev/sda 3

      echo "=== Estado tras growpart ==="
      lsblk
      echo ""

      echo "=== Redimensionar el Physical Volume ==="
      sudo pvresize /dev/sda3

      echo "=== Expandir Logical Volume ==="
      sudo lvextend -l +100%FREE /dev/cs_testlinux/root

      echo "=== Redimensionar sistema de archivos ==="
      sudo resize2fs /dev/cs_testlinux/root

      echo "=== Verificación final ==="
      lsblk
      df -h /
      vgs
      lvs
    displayName: "Expandir partición raíz"
    shell: bash
