trigger: none

pool:
  name: Default
  demands:
    - agent.name -equals testlinux

stages:
  - stage: ExpandDisk
    displayName: "Expand root partition on testlinux"
    jobs:
      - job: ResizeRootPartition
        displayName: "Expand / partition with new disk space"
        steps:
          - script: |
              echo "=== Información antes de iniciar ==="
              lsblk
              df -h /
              sudo vgs

              echo "=== Paso 1: Expandir partición sda3 con growpart ==="
              sudo growpart /dev/sda 3

              echo "=== Paso 2: Redimensionar Physical Volume ==="
              sudo pvresize /dev/sda3

              echo "=== Paso 3: Extender Logical Volume ==="
              sudo lvextend -l +100%FREE /dev/cs_testlinux/root

              echo "=== Paso 4: Redimensionar sistema de archivos ext4 ==="
              sudo resize2fs /dev/cs_testlinux/root

              echo "=== Información final ==="
              lsblk
              df -h /
              sudo vgs
            displayName: "Expandir partición raíz automáticamente"
