trigger:
- main

pool:
  name: Default  # Asegúrate de que el agente testlinux esté en este pool

jobs:
- job: ExpandRootDisk
  displayName: Expandir partición raíz automáticamente
  steps:
  - script: |
      set -eux

      echo "=== Información del disco ==="
      lsblk
      df -h /

      echo "=== Paso 1: Ampliar partición física (sda3) ==="
      sudo growpart /dev/sda 3

      echo "=== Paso 2: Redimensionar Physical Volume (PV) ==="
      sudo pvresize /dev/sda3

      echo "=== Paso 3: Extender Logical Volume (LV) ==="
      sudo lvextend -l +100%FREE /dev/cs_testlinux/root

      echo "=== Paso 4: Detectar tipo de FS y redimensionar ==="
      FS_TYPE=$(df -T / | tail -1 | awk '{print $2}')
      echo "Tipo de sistema de archivos: $FS_TYPE"

      if [ "$FS_TYPE" = "ext4" ]; then
        sudo resize2fs /dev/cs_testlinux/root
      elif [ "$FS_TYPE" = "xfs" ]; then
        sudo xfs_growfs /
      else
        echo "Sistema de archivos no compatible: $FS_TYPE"
        exit 1
      fi

      echo "=== Información final ==="
      lsblk
      df -h /
    displayName: "Expandir partición raíz automáticamente"
