trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals testlinux

jobs:
- job: ExpandRootDisk
  displayName: Expandir partición raíz automáticamente
  steps:
  - script: |
      set -eux

      echo "=== Información del disco ==="
      lsblk
      df -h /

      echo "=== Paso 1: Detectar la partición del Physical Volume (PV) ==="
      PV_PART=$(pvs --no-headings -o pv_name | awk '{print $1}' | head -n1)
      echo "Physical Volume detectado: $PV_PART"

      DISK_DEV=$(lsblk -no pkname "$PV_PART")
      PART_NUM=$(echo "$PV_PART" | grep -o '[0-9]*$')
      echo "Disco base: /dev/$DISK_DEV"
      echo "Número de partición: $PART_NUM"

      echo "=== Paso 2: Ampliar partición física si es necesario ==="
      sudo growpart "/dev/$DISK_DEV" "$PART_NUM" || echo "growpart no hizo cambios o ya estaba extendida"

      echo "=== Paso 3: Redimensionar Physical Volume (PV) ==="
      sudo pvresize "$PV_PART"

      echo "=== Paso 4: Detectar volumen lógico (LV) raíz ==="
      LV_PATH=$(df / | tail -1 | awk '{print $1}')
      echo "Volumen lógico raíz: $LV_PATH"

      echo "=== Paso 5: Extender Logical Volume (LV) ==="
      sudo lvextend -l +100%FREE "$LV_PATH"

      echo "=== Paso 6: Detectar tipo de sistema de archivos y redimensionar ==="
      FS_TYPE=$(df -T / | tail -1 | awk '{print $2}')
      echo "Tipo de sistema de archivos: $FS_TYPE"

      case "$FS_TYPE" in
        ext4)
          sudo resize2fs "$LV_PATH"
          ;;
        xfs)
          sudo xfs_growfs /
          ;;
        btrfs)
          sudo btrfs filesystem resize max /
          ;;
        *)
          echo "Sistema de archivos no soportado: $FS_TYPE"
          exit 1
          ;;
      esac

      echo "=== Información final ==="
      lsblk
      df -h /
    displayName: "Expandir partición raíz automáticamente"