trigger: none  # Solo manual

parameters:
  - name: firstName
    displayName: "Nombre"
    type: string
    default: ""

  - name: lastName
    displayName: "Apellido"
    type: string
    default: ""

  - name: accountName
    displayName: "Nombre de cuenta (sAMAccountName)"
    type: string
    default: ""

  - name: password
    displayName: "Contraseña"
    type: string
    default: ""

pool:
  name: 'Default'  # Cambia si tu agente DC01 está en otro pool
  demands:
    - agent.name -equals DC01

steps:
  - powershell: |
      Import-Module ActiveDirectory

      if ("${{ parameters.firstName }}" -eq "" -or "${{ parameters.lastName }}" -eq "" -or "${{ parameters.accountName }}" -eq "" -or "${{ parameters.password }}" -eq "") {
        Write-Error "❌ Todos los parámetros son obligatorios."
        exit 1
      }

      $SecurePass = ConvertTo-SecureString "${{ parameters.password }}" -AsPlainText -Force
      $DisplayName = "${{ parameters.firstName }} ${{ parameters.lastName }}"

      # Ruta a la OU donde crear el usuario
      $OUPath = "OU=CITRIX,OU=USUARIO,OU=G_ALTER,DC=alter,DC=es"

      if (Get-ADUser -Filter { SamAccountName -eq "${{ parameters.accountName }}" }) {
        Write-Error "❌ El usuario '${{ parameters.accountName }}' ya existe."
        exit 1
      }

      New-ADUser `
        -Name $DisplayName `
        -GivenName "${{ parameters.firstName }}" `
        -Surname "${{ parameters.lastName }}" `
        -SamAccountName "${{ parameters.accountName }}" `
        -UserPrincipalName "${{ parameters.accountName }}@midominio.local" `
        -AccountPassword $SecurePass `
        -Enabled $true `
        -Path $OUPath

      Write-Host "✅ Usuario creado: $DisplayName en $OUPath"
    displayName: "Crear usuario en AD"
