trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals LENOVO-ALEX

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Compilando el proyecto en LENOVO-ALEX"
      displayName: 'Compilación'
